spring:
  application:
    name: S2
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server:
  port: 8080