version: '3'
services:
  eureka:
    image: swarm.inf.uniroma3.it:5000/eureka-server-img-9004
#    container_name: eureka 
#    ports:
#    - "8761:8761"
    deploy:
      placement:
        constraints: [node.role == manager]
  S1:
    image: swarm.inf.uniroma3.it:5000/info-attore-cloud-img-9004
#    ports: 
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1    
  S2:
    image: swarm.inf.uniroma3.it:5000/numero-film-cloud-img-9004
#    ports: 
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 1     
  S:
    image: swarm.inf.uniroma3.it:5000/main-service-cloud-img-9004
#    ports: 
#    - "8080"
    depends_on:
    - "eureka"
    deploy:
      mode: replicated
      replicas: 2    
  zuul:
    image: swarm.inf.uniroma3.it:5000/zuul-img-9004
#    container_name: zuul 
    depends_on:
    - "eureka"
    ports:
    - "9004:8080"